on:
  push:
    tags:
      - '*'
permissions:
  contents: read

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/matplotlib-inline
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Install built wheel
      run: pip install dist/*
    - name: Build package
      run: python -m build
    - name: Echo current tag
      run: echo ${{ github.ref }}
    - name: Get package version
      run: |
        PACKAGE_VERSION=$(python -c 'import matplotlib_inline; print(matplotlib_inline.__version__)')
        echo "Package version: $PACKAGE_VERSION"

    - name: Check tag and package version match
      run: |
        if [ "$GITHUB_REF" != "refs/tags/$PACKAGE_VERSION" ]; then
          echo "Tag and package version do not match. Aborting."
          exit 1
        fi
    # - name: Publish package
    #   uses: pypa/gh-action-pypi-publish@15c56dba361d8335944d31a2ecd17d700fc7bcbc

